import type { Metadata } from "next";

import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { CreateNodeDialog } from "@/components/app/dialogs/CreateNode";
import { ConfirmationDialog } from "@/components/app/dialogs/Confirmation";
import { UpdateNodeDialog } from "@/components/app/dialogs/UpdateNode";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Tree Data Structure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
        <CreateNodeDialog />
        <ConfirmationDialog />
        <UpdateNodeDialog />
      </body>
    </html>
  );
}
